name: CI

on:
  push:
    branches:
      - main   # Change to your main branch if different
  pull_request:
    branches:
      - main   # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install


